# Generated by Django 3.1 on 2021-03-10 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walletApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='minBalance',
        ),
    ]
