# Generated by Django 3.1 on 2021-03-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletApp', '0002_remove_wallet_minbalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='phoneNumber',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
